<a href="https://colab.research.google.com/github/Yuyang-Yao/Math_-5750_Project3/blob/main/project3_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Math 5750/6880: Mathematics of Data Science \
Project 3

# 1. Fashion-MNIST image classification using sklearn

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.datasets import load_iris, make_moons, load_breast_cancer, fetch_california_housing
from sklearn.datasets import get_data_home
# from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LinearRegression
from scipy import io #will use this to load matlab data

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
import time

In [ ]:
from tensorflow.keras.datasets import fashion_mnist
from sklearn.preprocessing import StandardScaler

# Load Fashion-MNIST
# Classes (0-9): T-shirt/top, Trouser, Pullover, Dress, Coat, Sandal, Shirt, Sneaker, Bag, Ankle boot
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
X_train = X_train.reshape(len(X_train), -1)
X_test  = X_test.reshape(len(X_test), -1)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
print(X_train.shape) # around 15% test set

(60000, 784)


In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# your code here

In [ ]:
model_Q1_0 = MLPClassifier(hidden_layer_sizes=(256,128,64), max_iter=100, alpha=1e-4, tol=0.001,
                           #max_iter is number of epoch, not the number of gradient steps.
                           learning_rate='constant', # defalt
                    solver='adam', verbose=True, random_state=1,
                    learning_rate_init=.001)# defalt initial learning rate 0.001

start_t_adam_0 = time.time()
model_Q1_0.fit(X_train , y_train)
end_t_adam_0=time.time()
train_t_adm_0=end_t_adam_0-start_t_adam_0
print('training time for adam:', train_t_adm_0)

Iteration 1, loss = 0.45080846
Iteration 2, loss = 0.31725106
Iteration 3, loss = 0.28263321
Iteration 4, loss = 0.25067218
Iteration 5, loss = 0.23488814
Iteration 6, loss = 0.21322267
Iteration 7, loss = 0.19640196
Iteration 8, loss = 0.18487083
Iteration 9, loss = 0.16700078
Iteration 10, loss = 0.15342313
Iteration 11, loss = 0.14547729
Iteration 12, loss = 0.13270646
Iteration 13, loss = 0.12424172
Iteration 14, loss = 0.11561063
Iteration 15, loss = 0.10759347
Iteration 16, loss = 0.10313073
Iteration 17, loss = 0.09523209
Iteration 18, loss = 0.08970548
Iteration 19, loss = 0.08718528
Iteration 20, loss = 0.08431110
Iteration 21, loss = 0.07645283
Iteration 22, loss = 0.06955433
Iteration 23, loss = 0.06628050
Iteration 24, loss = 0.06743803
Iteration 25, loss = 0.06206500
Iteration 26, loss = 0.05337409
Iteration 27, loss = 0.05924098
Iteration 28, loss = 0.06294746
Iteration 29, loss = 0.05519073
Iteration 30, loss = 0.04693585
Iteration 31, loss = 0.05348680
Iteration 32, los

In [ ]:
print('After ', model_Q1_0.n_iter_, ' iterations, the loss is ', model_Q1_0.loss_)#loss??how do I know how many hiddern layers??
#print('model coef shapes')
#[print(coef.shape) for coef in model_Q1_0.coefs_]
#print('model coefs')
#[print(coef) for coef in model_Q1_0.coefs_]
#print('model intercepts')
#[print(coef) for coef in model_Q1_0.intercepts_]

#print(model_Q1_0.get_params())

# For binary classification, the activation function for output layer is logistic function:
#print(model_Q1_0.out_activation_)

After  63  iterations, the loss is  0.04214170700087341


In [ ]:
print(model_Q1_0.out_activation_)

softmax


In [ ]:
print(model_Q1_0.get_params())

{'activation': 'relu', 'alpha': 0.0001, 'batch_size': 'auto', 'beta_1': 0.9, 'beta_2': 0.999, 'early_stopping': False, 'epsilon': 1e-08, 'hidden_layer_sizes': (256, 128, 64), 'learning_rate': 'constant', 'learning_rate_init': 0.001, 'max_fun': 15000, 'max_iter': 100, 'momentum': 0.9, 'n_iter_no_change': 10, 'nesterovs_momentum': True, 'power_t': 0.5, 'random_state': 1, 'shuffle': True, 'solver': 'adam', 'tol': 0.001, 'validation_fraction': 0.1, 'verbose': True, 'warm_start': False}


In [ ]:
y_pred_Q1_0 = model_Q1_0 .predict(X_test)
cm_Q1_0 = confusion_matrix(y_test , y_pred_Q1_0)
print(cm_Q1_0 )

[[853   1  17  17   4   1  97   0  10   0]
 [  4 983   3   5   3   0   1   0   1   0]
 [ 21   2 853   6  46   1  69   0   2   0]
 [ 19   7  17 880  40   1  27   0   9   0]
 [  0   0 132  32 766   0  67   0   3   0]
 [  0   0   0   2   0 940   0  44   1  13]
 [124   2  95  23  50   0 697   0   9   0]
 [  0   0   0   0   0   4   0 977   1  18]
 [  6   2   3   2   5   2   8   2 970   0]
 [  0   0   0   0   0   7   1  45   2 945]]


In [ ]:
print(classification_report(y_test, y_pred_Q1_0))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      1000
           1       0.99      0.98      0.98      1000
           2       0.76      0.85      0.80      1000
           3       0.91      0.88      0.89      1000
           4       0.84      0.77      0.80      1000
           5       0.98      0.94      0.96      1000
           6       0.72      0.70      0.71      1000
           7       0.91      0.98      0.94      1000
           8       0.96      0.97      0.97      1000
           9       0.97      0.94      0.96      1000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



In [ ]:
model_Q1_1 = MLPClassifier(hidden_layer_sizes=(256,128,64), max_iter=100, alpha=1e-4, tol=0.001,
                           learning_rate='invscaling',
                    solver='adam', verbose=True, random_state=1,
                    learning_rate_init=.0001)# defalt initial learning rate 0.001
#hidden_layer_sizes=(3,4,5) means the neural network has three hidden layers: the first with 3 neurons, the second with 4 neurons, and the third with 5 neurons, progressively increasing complexity.


Iteration 1, loss = 0.72294141
Iteration 2, loss = 0.40810871
Iteration 3, loss = 0.35682974
Iteration 4, loss = 0.32694278
Iteration 5, loss = 0.30534464
Iteration 6, loss = 0.28818625
Iteration 7, loss = 0.27205891
Iteration 8, loss = 0.26042186
Iteration 9, loss = 0.24801232
Iteration 10, loss = 0.23713389
Iteration 11, loss = 0.22802399
Iteration 12, loss = 0.21782458
Iteration 13, loss = 0.20973183
Iteration 14, loss = 0.20018857
Iteration 15, loss = 0.19273993
Iteration 16, loss = 0.18535224
Iteration 17, loss = 0.17797953
Iteration 18, loss = 0.17120031
Iteration 19, loss = 0.16443036
Iteration 20, loss = 0.15808390
Iteration 21, loss = 0.15141290
Iteration 22, loss = 0.14619280
Iteration 23, loss = 0.14001010
Iteration 24, loss = 0.13416428
Iteration 25, loss = 0.12990066
Iteration 26, loss = 0.12424877
Iteration 27, loss = 0.11908487
Iteration 28, loss = 0.11383466
Iteration 29, loss = 0.10909232
Iteration 30, loss = 0.10534406
Iteration 31, loss = 0.10004920
Iteration 32, los

C:\Users\yaoyuyang\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(256, 128, 64), learning_rate='invscaling',
              learning_rate_init=0.0001, max_iter=100, random_state=1,
              tol=0.001, verbose=True)

In [ ]:
start_t_adam_1 = time.time()
model_Q1_1.fit(X_train , y_train)
end_t_adam_1=time.time()
train_t_adm_1=end_t_adam_1-start_t_adam_1
print('training time for adam:', train_t_adm_1)

In [ ]:
y_pred_Q1_1 = model_Q1_1 .predict(X_test)
cm_Q1_1 = confusion_matrix(y_test , y_pred_Q1_1)
print(cm_Q1_1 )

[[860   0  22  12   2   0  96   0   8   0]
 [  7 972   0  18   1   0   1   0   1   0]
 [ 20   1 831   9  87   1  48   0   3   0]
 [ 31   3   9 889  37   1  23   0   7   0]
 [  1   1  78  29 852   0  36   0   3   0]
 [  0   0   0   1   0 962   0  18   0  19]
 [147   1  84  25  88   1 644   0  10   0]
 [  0   0   0   0   0  21   0 934   0  45]
 [ 10   0   5   3   4   5   6   2 965   0]
 [  0   0   0   0   0   6   1  16   0 977]]


In [ ]:
print(classification_report(y_test, y_pred_Q1_1))

              precision    recall  f1-score   support

           0       0.80      0.86      0.83      1000
           1       0.99      0.97      0.98      1000
           2       0.81      0.83      0.82      1000
           3       0.90      0.89      0.90      1000
           4       0.80      0.85      0.82      1000
           5       0.96      0.96      0.96      1000
           6       0.75      0.64      0.69      1000
           7       0.96      0.93      0.95      1000
           8       0.97      0.96      0.97      1000
           9       0.94      0.98      0.96      1000

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000



# lbfgs optimization (Quasi-Newton methods)

In [ ]:
model_Q1_lbfgs_1 = MLPClassifier(hidden_layer_sizes=(256,128,60), max_iter=500, alpha=1e-4, tol=0.001,
                                 # run on smaller neurons to increase speed
                    solver='lbfgs', activation='tanh',verbose=True, max_fun=100000)#defalt 15000, max_fun=Maximum number of loss function calls??

need to compute hessian (second order der), but relu does not have non-zero hessian, so not use relu here


LBFGS works best with smooth activations like tanh or logistic, not ReLU, since ReLU’s nondifferentiability disrupts LBFGS’s second-order gradient updates.

tanh (-1–1, centered at 0), more stable than relu. Here need to compute Hessian

In [ ]:
start_t_lbfgs_1 = time.time()
model_Q1_lbfgs_1 .fit(X_train , y_train)
end_t_lbfgs_1=time.time()
train_t_lbfgs_1=end_t_lbfgs_1-start_t_lbfgs_1
print('training time for lbfgs, quasi-newton:', train_t_lbfgs_1)

training time for lbfgs, quasi-newton: 21006.547500371933


In [ ]:
y_pred_Q1_lbfgs_1 = model_Q1_lbfgs_1 .predict(X_test)
cm_Q1_lbfgs_1 = confusion_matrix(y_test , y_pred_Q1_lbfgs_1)
print(cm_Q1_lbfgs_1 )

[[822   0  16  23   2   1 124   0  12   0]
 [  2 970   1  19   3   0   5   0   0   0]
 [ 18   0 801  13  92   1  70   1   4   0]
 [ 25  12  12 875  37   1  32   0   6   0]
 [  5   0  89  31 819   1  51   0   4   0]
 [  2   0   0   1   0 948   0  25   1  23]
 [117   3  74  29  67   0 698   0  12   0]
 [  0   0   0   0   0  23   0 953   0  24]
 [  6   1   9   4   4   3  10   3 960   0]
 [  0   0   1   0   0  11   1  32   0 955]]


In [ ]:
print(classification_report(y_test, y_pred_Q1_lbfgs_1 ))

              precision    recall  f1-score   support

           0       0.82      0.82      0.82      1000
           1       0.98      0.97      0.98      1000
           2       0.80      0.80      0.80      1000
           3       0.88      0.88      0.88      1000
           4       0.80      0.82      0.81      1000
           5       0.96      0.95      0.95      1000
           6       0.70      0.70      0.70      1000
           7       0.94      0.95      0.95      1000
           8       0.96      0.96      0.96      1000
           9       0.95      0.95      0.95      1000

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000



# Sgd

In [ ]:
model_Q1_sde_1 = MLPClassifier(hidden_layer_sizes=(256,128,64), max_iter=100, alpha=1e-4, tol=0.001,
                           learning_rate='adaptive',# hopefully this will increase converge speed
                    solver='sgd', verbose=True, random_state=1, activation='tanh',
                    learning_rate_init=.0002)# increase a bit from defalt to let it converge within 100 epoch

In [ ]:
start_t_sde_1 = time.time()
model_Q1_sde_1 .fit(X_train , y_train)
end_t_sde_1=time.time()
train_t_sde_1=end_t_sde_1-start_t_sde_1
print('training time for lbfgs, quasi-newton:', train_t_sde_1)

Iteration 1, loss = 1.36553740
Iteration 2, loss = 0.85515993
Iteration 3, loss = 0.73259465
Iteration 4, loss = 0.66818431
Iteration 5, loss = 0.62573468
Iteration 6, loss = 0.59462672
Iteration 7, loss = 0.57046505
Iteration 8, loss = 0.55085539
Iteration 9, loss = 0.53443662
Iteration 10, loss = 0.52053236
Iteration 11, loss = 0.50843401
Iteration 12, loss = 0.49782722
Iteration 13, loss = 0.48838132
Iteration 14, loss = 0.47989697
Iteration 15, loss = 0.47217876
Iteration 16, loss = 0.46519692
Iteration 17, loss = 0.45876987
Iteration 18, loss = 0.45284980
Iteration 19, loss = 0.44735508
Iteration 20, loss = 0.44218082
Iteration 21, loss = 0.43742508
Iteration 22, loss = 0.43289349
Iteration 23, loss = 0.42862428
Iteration 24, loss = 0.42460746
Iteration 25, loss = 0.42083486
Iteration 26, loss = 0.41714924
Iteration 27, loss = 0.41373115
Iteration 28, loss = 0.41040355
Iteration 29, loss = 0.40729483
Iteration 30, loss = 0.40420215
Iteration 31, loss = 0.40133626
Iteration 32, los

C:\Users\yaoyuyang\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
print('training time for sgd:', train_t_sde_1)

training time for sgd: 807.1053051948547


In [ ]:
y_pred_Q1_sde_1 = model_Q1_sde_1 .predict(X_test)
cm_Q1_sde_1 = confusion_matrix(y_test , y_pred_Q1_sde_1)
print(cm_Q1_sde_1 )

[[830   0  12  40   4   2 102   0  10   0]
 [  4 959   6  23   3   0   3   0   2   0]
 [ 20   3 783  14 105   2  68   0   5   0]
 [ 17   8   9 895  37   1  30   0   3   0]
 [  0   0 107  34 794   1  59   0   5   0]
 [  0   0   0   1   0 933   0  37   3  26]
 [143   1  93  34  74   0 639   0  16   0]
 [  0   0   0   0   0  24   0 944   0  32]
 [  2   1   4   9   4   6  13   4 955   2]
 [  0   0   0   0   0   9   1  38   0 952]]


In [ ]:
print(classification_report(y_test, y_pred_Q1_sde_1))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82      1000
           1       0.99      0.96      0.97      1000
           2       0.77      0.78      0.78      1000
           3       0.85      0.90      0.87      1000
           4       0.78      0.79      0.79      1000
           5       0.95      0.93      0.94      1000
           6       0.70      0.64      0.67      1000
           7       0.92      0.94      0.93      1000
           8       0.96      0.95      0.96      1000
           9       0.94      0.95      0.95      1000

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000



In [ ]:
model_Q1_sde_2 = MLPClassifier(hidden_layer_sizes=(256,128,64), max_iter=150, alpha=1e-4, tol=0.001, momentum=0.8, # deflat
                    solver='sgd', verbose=True, random_state=1, activation='relu',
                    learning_rate_init=.005, # a bit bigger than defalt hope to converge fatser, 0.0015 final loss>1, 0.002 loss about 0.47, accuracy 0.82
                    nesterovs_momentum=True, learning_rate='invscaling', power_t=0.5 # 0.5 in class said is best
)

In [ ]:
start_t_sde_2 = time.time()
model_Q1_sde_2 .fit(X_train , y_train)
end_t_sde_2=time.time()
train_t_sde_2=end_t_sde_2-start_t_sde_2


Iteration 1, loss = 0.67113590
Iteration 2, loss = 0.45706126
Iteration 3, loss = 0.45312296
Iteration 4, loss = 0.45195783
Iteration 5, loss = 0.45136630
Iteration 6, loss = 0.45097592
Iteration 7, loss = 0.45067650
Iteration 8, loss = 0.45042711
Iteration 9, loss = 0.45020622
Iteration 10, loss = 0.45000915
Iteration 11, loss = 0.44982896
Iteration 12, loss = 0.44966122
Iteration 13, loss = 0.44950295
Iteration 14, loss = 0.44935399
Iteration 15, loss = 0.44921133
Training loss did not improve more than tol=0.001000 for 10 consecutive epochs. Stopping.


decay quickly, but did not improve after second eporch, try smaller power?
loss

In [ ]:
print('training time for lbfgs, quasi-newton:', train_t_sde_2)

training time for lbfgs, quasi-newton: 155.66792488098145


In [ ]:
y_pred_Q1_sde_2 = model_Q1_sde_2 .predict(X_test)
cm_Q1_sde_2 = confusion_matrix(y_test , y_pred_Q1_sde_2)
print(cm_Q1_sde_2 )

[[801   1  15  59   5   4  98   0  17   0]
 [  3 942   9  36   7   0   2   0   1   0]
 [ 14   1 741   9 129   2  89   0  15   0]
 [ 35   8   9 867  36   1  39   0   5   0]
 [  0   3 106  32 756   0  95   0   8   0]
 [  0   1   0   1   0 888   0  64   4  42]
 [178   1 115  44 109   4 521   0  28   0]
 [  0   0   0   0   0  44   0 909   2  45]
 [  0   1   5  12   3  13  26   6 933   1]
 [  1   0   0   1   0  26   1  39   0 932]]


In [ ]:
print(classification_report(y_test, y_pred_Q1_sde_2))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79      1000
           1       0.98      0.94      0.96      1000
           2       0.74      0.74      0.74      1000
           3       0.82      0.87      0.84      1000
           4       0.72      0.76      0.74      1000
           5       0.90      0.89      0.90      1000
           6       0.60      0.52      0.56      1000
           7       0.89      0.91      0.90      1000
           8       0.92      0.93      0.93      1000
           9       0.91      0.93      0.92      1000

    accuracy                           0.83     10000
   macro avg       0.83      0.83      0.83     10000
weighted avg       0.83      0.83      0.83     10000



ReLU generally gives faster convergence with SGD in MLPs because it avoids vanishing gradients common in tanh and sigmoid, enabling stronger gradient flow and faster learning during optimization.

In [ ]:
model_Q1_sde_3 = MLPClassifier(hidden_layer_sizes=(256,128,64), max_iter=150, alpha=1e-4, tol=0.0005, momentum=0.8,
                               # since it converge slowly, drop tol to run more eporchs and see if loss keep drops
                    solver='sgd', verbose=True, random_state=1, activation='relu',
                    learning_rate_init=.006, # a bit bigger than defalt hope to converge fatser, 0.0015 final loss>1, 0.002 loss about 0.47, accuracy 0.82
                    nesterovs_momentum=True, learning_rate='invscaling', power_t=0.25 # get this converge slower and see what happens, really increase eporchs, waste time
)

In [ ]:
start_t_sde_3 = time.time()
model_Q1_sde_3 .fit(X_train , y_train)
end_t_sde_3=time.time()
train_t_sde_3=end_t_sde_3-start_t_sde_3

Iteration 1, loss = 0.64029938
Iteration 2, loss = 0.43122989
Iteration 3, loss = 0.42407763
Iteration 4, loss = 0.41910246
Iteration 5, loss = 0.41485451
Iteration 6, loss = 0.41110756
Iteration 7, loss = 0.40777320
Iteration 8, loss = 0.40476778
Iteration 9, loss = 0.40186828
Iteration 10, loss = 0.39924190
Iteration 11, loss = 0.39676007
Iteration 12, loss = 0.39446659
Iteration 13, loss = 0.39221277
Iteration 14, loss = 0.39010471
Iteration 15, loss = 0.38811215
Iteration 16, loss = 0.38617714
Iteration 17, loss = 0.38431309
Iteration 18, loss = 0.38254599
Iteration 19, loss = 0.38091556
Iteration 20, loss = 0.37922869
Iteration 21, loss = 0.37765035
Iteration 22, loss = 0.37613228
Iteration 23, loss = 0.37463351
Iteration 24, loss = 0.37320877
Iteration 25, loss = 0.37186464
Iteration 26, loss = 0.37041440
Iteration 27, loss = 0.36917934
Iteration 28, loss = 0.36786096
Iteration 29, loss = 0.36664997
Iteration 30, loss = 0.36540442
Iteration 31, loss = 0.36426145
Iteration 32, los

In [ ]:
y_pred_Q1_sde_3 = model_Q1_sde_3 .predict(X_test)
cm_Q1_sde_3 = confusion_matrix(y_test , y_pred_Q1_sde_3)
print(cm_Q1_sde_3 )

[[826   1  12  43   3   2 102   0  11   0]
 [  4 962   4  22   4   0   3   0   1   0]
 [ 14   3 785  15 109   2  67   0   5   0]
 [ 20  10  14 900  25   1  27   0   3   0]
 [  0   1 105  32 783   0  73   0   6   0]
 [  0   1   0   0   0 931   0  37   4  27]
 [130   1  96  42  79   1 635   1  15   0]
 [  0   0   0   0   0  30   0 939   1  30]
 [  0   1   3   7   6   6  16   5 955   1]
 [  0   0   0   1   0  15   1  40   0 943]]


In [ ]:
print(classification_report(y_test, y_pred_Q1_sde_3))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83      1000
           1       0.98      0.96      0.97      1000
           2       0.77      0.79      0.78      1000
           3       0.85      0.90      0.87      1000
           4       0.78      0.78      0.78      1000
           5       0.94      0.93      0.94      1000
           6       0.69      0.64      0.66      1000
           7       0.92      0.94      0.93      1000
           8       0.95      0.95      0.95      1000
           9       0.94      0.94      0.94      1000

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000



approximate runing time, adma>sgd>lbfgs
convergence speed: Adam>SGD (with nesterovs_momentum)

# 3. Fashion-MNIST image classification  using pytorch

In [ ]:
import numpy as np
from tensorflow.keras.datasets import fashion_mnist
import torch
from torch.utils.data import TensorDataset, DataLoader

# Load Fashion-MNIST
# Classes (0-9): T-shirt/top, Trouser, Pullover, Dress, Coat, Sandal, Shirt, Sneaker, Bag, Ankle boot
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

# scale to [0,1], add channel dimension -> (N, 1, 28, 28)
X_train = (X_train.astype("float32") / 255.0)[:, None, :, :]
X_test  = (X_test.astype("float32")  / 255.0)[:,  None, :, :]

y_train = y_train.astype(np.int64)
y_test  = y_test.astype(np.int64)

# train/val split: last 10k of train as validation
X_tr, X_val = X_train[:50000], X_train[50000:]
y_tr, y_val = y_train[:50000], y_train[50000:]

# wrap in PyTorch TensorDatasets and DataLoaders
train_ds = TensorDataset(torch.from_numpy(X_tr),  torch.from_numpy(y_tr))
val_ds   = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))
test_ds  = TensorDataset(torch.from_numpy(X_test), torch.from_numpy(y_test))

train_loader = DataLoader(train_ds, batch_size=128, shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=256, shuffle=False)
test_loader  = DataLoader(test_ds,  batch_size=256, shuffle=False)

In [ ]:
import torch.nn as nn
import torch.optim as optim

# In colab, you should ``change runtime type'' to GPU.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# your code here